import { AppItem } from "@/types";

export const APPS: AppItem[] = [
  {
    id: "app-001",
    name: "Générateur de rapports",
    description: "Automatise la création de rapports hebdomadaires à partir de données brutes. Génère des PDF structurés et les envoie par email aux parties prenantes.",
    category: "Analyse & Reporting",
    status: "active",
    url: "#",
    icon: "FileBarChart",
    color: "#3B82F6",
    tags: ["PDF", "Email", "Automatisation"],
    createdAt: "2024-01-15",
    usesN8N: true,
  },
  {
    id: "app-002",
    name: "Veille concurrentielle",
    description: "Collecte et analyse les données de veille marché quotidiennement. Consolide les informations dans un tableau de bord centralisé.",
    category: "Analyse & Reporting",
    status: "active",
    url: "#",
    icon: "TrendingUp",
    color: "#8B5CF6",
    tags: ["Scraping", "Analyse", "Dashboard"],
    createdAt: "2024-02-03",
    usesN8N: true,
  },
  {
    id: "app-003",
    name: "Chatbot Support Client",
    description: "Assistant IA intégré au site pour répondre aux questions fréquentes. Escalade automatiquement les cas complexes vers un agent humain.",
    category: "Communication",
    status: "active",
    url: "#",
    icon: "MessageSquare",
    color: "#10B981",
    tags: ["IA", "Support", "Chat"],
    createdAt: "2024-02-20",
    usesN8N: false,
  },
  {
    id: "app-004",
    name: "Synchronisation CRM",
    description: "Synchronise les données entre le CRM interne et les outils tiers (HubSpot, Salesforce). Élimine les doublons et normalise les entrées.",
    category: "Intégration",
    status: "active",
    url: "#",
    icon: "RefreshCw",
    color: "#F59E0B",
    tags: ["CRM", "Sync", "API"],
    createdAt: "2024-03-10",
    usesN8N: true,
  },
  {
    id: "app-005",
    name: "Pipeline de qualification leads",
    description: "Qualifie automatiquement les leads entrants selon des critères prédéfinis. Score et répartit les prospects entre les équipes commerciales.",
    category: "Automatisation",
    status: "new",
    url: "#",
    icon: "Filter",
    color: "#EF4444",
    tags: ["Leads", "Scoring", "Sales"],
    createdAt: "2024-03-28",
    usesN8N: true,
  },
  {
    id: "app-006",
    name: "Gestionnaire de tâches IA",
    description: "Priorise et distribue les tâches d'équipe grâce à l'intelligence artificielle. Génère des résumés de charge de travail hebdomadaires.",
    category: "Productivité",
    status: "beta",
    url: "#",
    icon: "CheckSquare",
    color: "#06B6D4",
    tags: ["IA", "Tâches", "Équipe"],
    createdAt: "2024-04-05",
    usesN8N: false,
  },
  {
    id: "app-007",
    name: "ETL Données Internes",
    description: "Pipeline d'extraction, transformation et chargement de données entre les bases internes. Garantit la cohérence des données en temps réel.",
    category: "Gestion de données",
    status: "active",
    url: "#",
    icon: "Database",
    color: "#6366F1",
    tags: ["ETL", "Data", "Pipeline"],
    createdAt: "2024-04-18",
    usesN8N: true,
  },
  {
    id: "app-008",
    name: "Alertes & Monitoring",
    description: "Surveille les métriques clés en temps réel et envoie des alertes multi-canaux (Slack, email, SMS) en cas d'anomalie détectée.",
    category: "Automatisation",
    status: "active",
    url: "#",
    icon: "Bell",
    color: "#F97316",
    tags: ["Monitoring", "Alertes", "Temps réel"],
    createdAt: "2024-05-02",
    usesN8N: true,
  },
];

export const CATEGORIES = [
  "Toutes",
  "Automatisation",
  "Analyse & Reporting",
  "Communication",
  "Productivité",
  "Intégration",
  "Gestion de données",
  "Autre",
] as const;

export const STATUS_CONFIG = {
  active: { label: "Actif", color: "text-emerald-600 bg-emerald-50 border-emerald-200" },
  beta: { label: "Bêta", color: "text-amber-600 bg-amber-50 border-amber-200" },
  maintenance: { label: "Maintenance", color: "text-red-600 bg-red-50 border-red-200" },
  new: { label: "Nouveau", color: "text-blue-600 bg-blue-50 border-blue-200" },
} as const;
